version: '3.9'
services:

#  db:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: images
#    ports:
#      - 3306:3306


  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db

